### DISCUSSION TITLE
builder runner options for riverpod generator

### DISCUSSION THREAD

**Discussion by dipakp2726** [rrousselGit/riverpod#2009] [Q&A] [answered]
i want to use build.yaml configs for riverpod so it scan lower number of files but I am not able find exact name of builder for riverpod generator.
i tried using below buts not working
- riverpod_generator
- riverpod_builder
- riverpod

```yaml
targets:
  $default:
    builders:
      riverpod_generator: riverpod_generator
        generate_for:
          include:
            - lib/models/**.dart
```
