### DISCUSSION TITLE
The argument type 'AutoDisposeNotifierProviderImpl<FavoritesId, List<String>>' can't be assigned to the parameter type 'AlwaysAliveProviderListenable<dynamic>'

### DISCUSSION THREAD

**Discussion by abikko** [rrousselGit/riverpod#2013] [General]
Code:
```
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'favorites_id.g.dart';

@riverpod
class FavoritesId extends _$FavoritesId {
  @override
  List<String> build() {
    return [];
  }

  void addFavorite(List<String> values) {
    List<String> list = state.addAllInState(values);
    state = list;
  }
}

```
Just runned with `flutter pub run build_runner build`
and also have pubspec.yaml:
```
dependencies:
  flutter_riverpod: ^2.0.2
  riverpod_annotation: ^1.0.4
  

dev_dependencies:
  build_runner: ^2.3.2
  riverpod_generator: ^1.0.6

```
