### DISCUSSION TITLE
dart_eval seems to stop custom_lint working.

### DISCUSSION THREAD

**Discussion by brilliapps** [rrousselGit/riverpod#3713] [Q&A] [answered]
Don't know where to post, it seems that it is better to do it here not on the dart_eval github repository.

I have pubspec.yaml relevant part like this:
```yaml
name: some_custom_lint_package_with_rules
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.4.4 <4.0.0"
dependencies:
  dart_eval: 
  # we will use analyzer for inspecting Dart files
  analyzer: 
  analyzer_plugin:
  # custom_lint_builder will give us tools for writing lints
  custom_lint_builder:
```
without the dart_eval entry all is ok. just adding dart_eval stops custom_lint working - probably not the analyzer itself (i am not that experienced to distinguish).

I guess both custom_lint and dart_eval are in conflict because they use analyzer, but as they were designed independently they were not made with this in mind how they will interact with each other.

Did anybody have such a problem in the past? Does anybody know what can be the reason?
