### DISCUSSION TITLE
[dart_custom_lints] Help Request: How to Propagate Custom Lints Using a Centralized Lint Package?

### DISCUSSION THREAD

**Discussion by MobiliteDev** [rrousselGit/riverpod#3780] [Q&A] [answered]
Hi everyone,

I'm trying to set up a centralized system for managing lints across multiple projects, including some custom lints using the `custom_lint` package. Here is my setup, but I'm struggling to get it working correctly.

**Overview of My Setup:**
I have a three-step setup to manage lints:

1. **Custom Lint Package (`my_custom_lints`)**: This package contains all my custom lints, defined with `custom_lint_builder`.

2. **Central Lint Package (`central_lint_package`)**: This package selects some default Flutter lints and also includes my custom lints from `my_custom_lints`. I want this to act as the main lint configuration for all projects, without each project needing to manually include `my_custom_lints` or configure the `custom_lint` plugin.

3. **Final Project (`final_project`)**: This is a Flutter project that depends on `central_lint_package` for its lint rules. It includes the centralized lint configuration through `analysis_options.yaml`.

**Structure and Configuration:**

- `my_custom_lints`
  - Defines custom lints using `custom_lint_builder`.
- `central_lint_package`
  - Depends on `my_custom_lints` and `custom_lint`.
  - Contains `analysis_options.yaml` that includes `custom_lint`.
  - Exports `my_custom_lints`.
- `final_project`
  - Depends on `central_lint_package`.
  - Includes `central_lint_package` in its `analysis_options.yaml`.

**What I'm Trying to Achieve:**
I want all projects that depend on `central_lint_package` to automatically have access to the custom lints defined in `my_custom_lints`. Ideally, this would mean:

- No need to manually add `custom_lint` or `my_custom_lints` in every project.
- All projects just include `central_lint_package` in `analysis_options.yaml` and get both the standard lints and the custom lints.

**The Issue I'm Facing:**
I don't seem to be able to get the `custom_lint` plugin to recognize the custom lints when included this way. I keep running into issues where the `custom_lint_client` doesn't seem to find the exported lints from `central_lint_package`.

Here is a minimal reproducible example of my setup:

- `my_custom_lints/`

  - **`pubspec.yaml`**:
    ```yaml
    name: my_custom_lints
    description: A custom lint package with custom rules.
    version: 0.0.1

    environment:
      sdk: ">=2.17.0 <3.0.0"

    dependencies:
      custom_lint_builder: ^0.6.0
    ```

  - **`lib/my_custom_lints.dart`**:
    ```dart
    import 'package:custom_lint_builder/custom_lint_builder.dart';

    Plugin createPlugin() => ExampleCustomLintPlugin();

    class ExampleCustomLintPlugin extends Plugin {
      @override
      List<LintRule> getLintRules(CustomLintConfigs configs) {
        return [
          ExampleLintRule(),
        ];
      }
    }

    class ExampleLintRule extends LintRule {
      ExampleLintRule()
          : super(
            code: LintCode(
              name: 'example_rule',
              problemMessage: 'This is an example lint rule',
            ),
          );

      @override
      void run(CustomLintResolver resolver, ErrorReporter reporter, CustomLintConfigs configs) {
        // Implementation of the lint rule logic here
      }
    }
    ```

- `central_lint_package/`

  - **`pubspec.yaml`**:
    ```yaml
    name: central_lint_package
    description: A lint package combining custom lints and standard lints.
    version: 0.0.1

    environment:
      sdk: ">=2.17.0 <3.0.0"

    dependencies:
      custom_lint: ^0.6.0
      my_custom_lints:
        path: ../my_custom_lints
    ```

  - **`analysis_options.yaml`**:
    ```yaml
    analyzer:
      plugins:
        - custom_lint

    linter:
      rules:
        - always_declare_return_types
        - prefer_const_constructors
    ```

  - **`lib/central_lint_package.dart`**:
    ```dart
    library central_lint_package;

    export 'package:my_custom_lints/my_custom_lints.dart';
    ```

- `final_project/`

  - **`pubspec.yaml`**:
    ```yaml
    name: final_project
    description: A Flutter project that uses custom lints.
    version: 0.0.1

    environment:
      sdk: ">=2.17.0 <3.0.0"

    dependencies:
      flutter:
        sdk: flutter

    dev_dependencies:
      central_lint_package:
        path: ../central_lint_package
      custom_lint: ^0.6.0
    ```

  - **`analysis_options.yaml`**:
    ```yaml
    include: package:central_lint_package/analysis_options.yaml
    ```

  - **`lib/main.dart`**:
    ```dart
    import 'package:flutter/material.dart';

    void main() {
      runApp(const MyApp());
    }

    class MyApp extends StatelessWidget {
      const MyApp({super.key});

      @override
      Widget build(BuildContext context) {
        return MaterialApp(
          title: 'Flutter Demo',
          theme: ThemeData(
            primarySwatch: Colors.blue,
          ),
          home: const MyHomePage(),
        );
      }
    }

    class MyHomePage extends StatelessWidget {
      const MyHomePage({super.key});

      @override
      Widget build(BuildContext context) {
        return Scaffold(
          appBar: AppBar(
            title: const Text('Flutter Demo Home Page'),
          ),
          body: const Center(
            child: Text('Hello World!'),
          ),
        );
      }
    }
    ```

Even after setting it up this way, my custom lints are not being recognized in the `final_project`. I suspect there might be something I don't fully understand about how `custom_lint` propagates plugins across dependencies or how the analyzer processes them.

**My Question:**
Is it possible to achieve this type of centralized setup with `custom_lint`, where the `custom_lint` plugin and custom lints are inherited by a project through an intermediate lint package (`central_lint_package`)? Or is there a limitation that prevents this from working as intended?

Thanks a lot in advance for your help!
