### DISCUSSION TITLE
Does Riverpod Generator support package based imports in the part directive?

### DISCUSSION THREAD

**Discussion by The-Funk** [rrousselGit/riverpod#4038] [Q&A]
I have a build.yaml for build_runner that looks something like this:

```yaml
targets:
  $default:
    builders:
      dart_mappable_builder:
        options:
          build_extensions:
            'lib/{{path}}/{{file}}.dart':
              - 'lib/generated/{{path}}/{{file}}.mapper.dart'
              - 'lib/generated/{{path}}/{{file}}.init.dart'
      source_gen:combining_builder:
        options:
          build_extensions:
            'lib/{{path}}/{{file}}.dart':
              - 'lib/{{path}}/generated/{{file}}.g.dart'
```

In my providers created with the `@riverpod` annotation, I can successfully use part directives that look like this:
`part 'generated/paginated_community.g.dart';`

This allows me to create a generated directory next to my providers, so that if I have a directory with multiple provider files in it, all their generated code gets neatly tucked away in a singular generated folder.

However if I edit the above build_yaml to move the path after generated, because I want to move all of my generated files into a generated directory at the root of lib like I do with dart_mappable, and then I reference that path like this:
`part 'package:my_cool_package/generated/some/path/paginated_community.g.dart';`

Riverpod generator seems to take issue with this. 

Is this a build_runner issue or something in the riverpod_generator?
