### ISSUE TITLE
codegen looks awesome. any release date or tutorial or sample code

### ISSUE THREAD

**Issue by neiljaywarner** [rrousselGit/riverpod#1593]
Just watched the flutter vikings session and it looks awesome. I looked around awhile and couldn't find hardly anything on the codgen-which i get it, it's new, but how do i use at-riverpod?

I'm not sure if i should delete/close this issue, i am starting to see it woudl take some time to get usable for wider release, definitely curious how it works with autodispose etc.... was a great demo.

**Comment by TimWhiting** [comment]
Feel free to experiment by using a git dependency:
```yaml
dependencies:
  flutter:
    sdk: flutter
  riverpod: 
    git:
      url: https://github.com/rrousselGit/riverpod
      path: packages/riverpod
  flutter_riverpod: 
    git:
      url: https://github.com/rrousselGit/riverpod
      path: packages/flutter_riverpod
  hooks_riverpod: 
    git:
      url: https://github.com/rrousselGit/riverpod
      path: packages/hooks_riverpod
  riverpod_annotation: 
    git:
      url: https://github.com/rrousselGit/riverpod
      path: packages/riverpod_annotation
  flutter_hooks: ^0.18.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  riverpod_generator:
    git:
      url: https://github.com/rrousselGit/riverpod
      path: packages/riverpod_generator
```

Just remember it is still experimental. But, I'm sure feedback is welcome.
