### ISSUE TITLE
Support generated types as return type for generated providers

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/riverpod#1782]
I have not yet created a standalone example, but if it helps,  the Stream class is being generated from my model by the firestore ODM generator:

```dart
@riverpod
Stream<EventQuerySnapshot> currentEvents(CurrentEventsRef ref, {DateTime? dateTime,
            List<EventCategory> categoryFilter = const [] }) {
    var db = ref.watch(databaseProvider);
    return db.getCurrentEventStream(date: dateTime, categoryFilter:categoryFilter );
}
```

In the above, `EventQuerySnapshot` is generated via `@firestoreSerializable` annotation on my `Event`  class.

So this has something to do with the order in which annotations are processed by build runner?

_Originally posted by @wstrange in https://github.com/rrousselGit/riverpod/issues/1663#issuecomment-1281663846_

**Comment by matthewjsummers** [comment]
Are there any plans on fixing this? We use Drift to generate our models and we can't use the `@riverpod` annotation for `Notifiers` as riverpod annotations can't seem to find them.

**Comment by rrousselGit** [comment]
Provably not before Metaprogramming

**Comment by JonasWanke** [comment]
We had a similar problem combining Riverpod with Freezed but fixed it with the solution suggested in https://github.com/trevorwang/retrofit.dart/issues/578#issuecomment-1583804327. In our project's [`build.yaml`](https://pub.dev/packages/build_config) (in the same directory as `pubspec.yaml`), we added the following configuration:

```yaml
global_options:
  freezed:
    runs_before:
      - riverpod_generator
```

For Firestore, the config would probably look like this (not tested):

```yaml
global_options:
  cloud_firestore_odm_generator:
    runs_before:
      - riverpod_generator
```
