### ISSUE TITLE
[riverpod_lint] - A lint plugin threw an exceptiondart(custom_lint_get_lint_fail)

### ISSUE THREAD

**Issue by emirchus** [rrousselGit/riverpod#2173]
**Describe the bug**
Just when I install it, throws an exception

**To Reproduce**
Install and configure the analyzer

pubspec.yaml:
```yaml
dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  mockito: ^5.3.2
  injectable_generator: ^2.1.3
  custom_lint:
  riverpod_lint:
```

analysis_options.yaml:
````yaml
include: package:flutter_lints/flutter.yaml

linter:
  rules:

analyzer:
  plugins:
    - custom_lint

custom_lint:
  enable_all_lint_rules: true
  rules:

```

**Expected behavior**
It should work
