### ISSUE TITLE
Generated code for provider class that shoud provide a built-in Flutter type returns `dynamic` instead

### ISSUE THREAD

**Issue by jagged3dge** [rrousselGit/riverpod#2273]
When generating a provider which returns a Flutter built-in type using the latest versions of `flutter_riverpod`, `riverpod_annotation` & `riverpod_generator`, there seems to be an issue with the generated provider causing the provided value to be of type `dynamic` instead of the built-in type.

This does not seem to happen when generating code for provider classes that return custom classes — only Flutter built-ins.

I'm using:

```yaml
// excerpt from pubspec.yaml
environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: 3.7.6

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: 2.3.0
  riverpod_annotation: 2.0.0

devDependencies:
  build_runner: 2.3.3
  riverpod_generator: 2.0.0
```
**To Reproduce**

I'm using the following provider to provide `Locale` from `package:flutter/widgets.dart`:

```dart
// lib/providers/default_color_provider.dart
import 'package:flutter/material.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'default_color_provider.g.dart';

@riverpod
class DefaultColor extends _$DefaultColor {
  @override
  Color build() {
    return Colors.blue;
  }
}

```
This generates an `default_color_provider.g.dart` file with the following contents:
```dart
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'default_color_provider.dart';

// **************************************************************************
// RiverpodGenerator
// **************************************************************************

String _$defaultColorHash() => r'59bf966981fbc6d6d7c389ad7cdc35046e20c57b';

/// See also [DefaultColor].
@ProviderFor(DefaultColor)
final defaultColorProvider =
    AutoDisposeNotifierProvider<DefaultColor, dynamic>.internal( // incorrectly generated `dynamic`
  DefaultColor.new,
  name: r'defaultColorProvider',
  debugGetCreateSourceHash:
      const bool.fromEnvironment('dart.vm.product') ? null : _$defaultColorHash,
  dependencies: null,
  allTransitiveDependencies: null,
);

typedef _$DefaultColor = AutoDisposeNotifier<dynamic>;  // incorrectly generated `dynamic`
// ignore_for_file: unnecessary_raw_strings, subtype_of_sealed_class, invalid_use_of_internal_member, do_not_use_environment, prefer_const_constructors, public_member_api_docs, avoid_private_typedef_functions
```

**Expected behavior**

Consumer of a provider that is supposed to return a `Color` type object, must receive a `Color` typed object, not `dynamic`.
