### ISSUE TITLE
"dart run custom_lint" gives error

### ISSUE THREAD

**Issue by agufagit** [rrousselGit/riverpod#2387]
**Describe the bug**
`dart run custom_lint` gives error:
```
Building package executable... (6.5s)
Built custom_lint:custom_lint.
Failed to start plugins
The request analysis.setContextRoots failed with the following error:
RequestErrorCode.PLUGIN_ERROR
Bad state: Failed to start the plugins.
at:
#0      _SocketCustomLintServerToClientChannel._checkInitializationFail.<anonymous closure> (package:custom_lint/src/v2/server_to_client_channel.dart:489:11)
#1      _rootRunUnary (dart:async/zone.dart:1406:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1307:19)
<asynchronous suspension>
#3      Future.any.onValue (dart:async/future.dart:612:5)
<asynchronous suspension>
```

**To Reproduce**

`dart run custom_lint` in commandline

**Expected behavior**
run custom_lint

**Environment**
windows 11 wsl2, flutter 3.7.7, dart 2.19.4, DevTools 2.20.1

**analysis_options.yaml**
```
include: package:flutter_lints/flutter.yaml

linter:
  rules:

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  plugins:
    - custom_lint
```
