### ISSUE TITLE
riverpod_lint incompatible with auto_route

### ISSUE THREAD

**Issue by rob32** [rrousselGit/riverpod#2410]
**Describe the bug**

riverpod_lint ^1.1.6 is incompatible with auto_route_generator >=6.0.1.

`flutter pub get` throws me this:

> Resolving dependencies...
> Because no versions of riverpod_lint match >1.1.6 <2.0.0 and riverpod_lint 1.1.6 depends on custom_lint_builder ^0.3.2, riverpod_lint ^1.1.6 requires custom_lint_builder ^0.3.2.
> And because no versions of custom_lint_builder match >0.3.2 <0.4.0, riverpod_lint ^1.1.6 requires custom_lint_builder 0.3.2.
> And because custom_lint_builder 0.3.2 depends on analyzer >=5.7.0 <5.8.0 and auto_route_generator >=6.0.1 depends on analyzer ^5.9.0, riverpod_lint ^1.1.6 is incompatible with auto_route_generator >=6.0.1.
> So, because add_name_app depends on both auto_route_generator ^6.0.2 and riverpod_lint ^1.1.6, version solving failed.
> pub get failed

Is it possible that riverpod_lint also use `analyzer ^5.9.0` ?

**To Reproduce**

My Pubspec

```yaml
dependencies:
  auto_route: ^6.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.2
  riverpod_annotation: ^2.0.2

dev_dependencies:
  auto_route_generator: ^6.0.2
  build_runner: ^2.3.3
  custom_lint: ^0.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.1.4
  riverpod_lint: ^1.1.6
```

**Expected behavior**
The use of _riverpod_lint_ and _auto_route_ at the same time
