### ISSUE TITLE
flutter_riverpod ^2.3.6 is forbidden

### ISSUE THREAD

**Issue by osodev99** [rrousselGit/riverpod#2714]
**Describe the bug**
i can't use flutter_riverpod 2.3.6

**To Reproduce**

create new project and add dependency in pubspec.yaml

```
environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

```
then use flutter pub get, and get error 

```
Resolving dependencies... 
Because no versions of flutter_riverpod match 2.3.6 and no versions of flutter_riverpod match >2.3.6 <3.0.0, flutter_riverpod ^2.3.6 is forbidden.
So, because test_riverpd depends on flutter_riverpod ^2.3.6, version solving failed.
```
