### ISSUE TITLE
Before Error. After Ok. No informations.

### ISSUE THREAD

**Issue by catalunha** [rrousselGit/riverpod#2962]
**Describe the bug**
Thank you Remi.
But let's go to a scenario that I would like your analysis (or your colleagues) of where my error is. Because I think it's difficult to be Riverpod's mistake. But let's go.
Consider the simple provider:
```dart
@riverpod
FutureOr<List<RegisterModel>> registersController(
    RegistersControllerRef ref) async {
  final profile = ref.read(meProfileProvider)!;
  final districtIds = profile.districtIds;
  if (districtIds != null && districtIds.isNotEmpty) {
    final districtIdsFirst = districtIds[0];
    // before. Error
    // ref.read(districtCurrentProvider.notifier).set(districtIdsFirst.name);
    final result =
        await ref.read(registerRepositoryProvider).list(districtIdsFirst.id);
    //after. Ok
    ref.read(districtCurrentProvider.notifier).set(districtIdsFirst.name);
    List<RegisterModel> list = switch (result) {
      Failure() => const [],
      Success(:final value) => value,
    };
    ref.read(registersDataProvider.notifier).set(list);
    return list;
  }
  return [];
}
```
and
```dart
@Riverpod(keepAlive: true)
class DistrictCurrent extends _$DistrictCurrent {
  @override
  String build() {
    return '.?.';
  }

  void set(String value) {
    state = value;
  }
}
```
If I use districtCurrentProvider before. Generates an error without any description in the console when searching for registerRepositoryProvider.
But if I use districtCurrentProvider afterwards. Everything works perfectly.
Follow the other providers
```dart
@Riverpod(keepAlive: true)
RegisterRepository registerRepository(RegisterRepositoryRef ref) {
  return RegisterRepositoryImpl(dioClient: ref.read(dioClientProvider));
}
```
```dart

class RegisterRepositoryImpl implements RegisterRepository {
  final DioClient dioClient;
  RegisterRepositoryImpl({
    required this.dioClient,
  });
  @override
  Future<Either<RepositoryException, List<RegisterModel>>> list(
      String? districtId) async {
    try {
      List<dynamic> dataFinal;
      if (districtId == null) {
        final Response(:List data) = await dioClient.auth.get(
          ApiV1EndPoints.register,
        );
        dataFinal = data;
      } else {
        final Response(:List data) = await dioClient.auth.get(
          ApiV1EndPoints.register,
          queryParameters: {
            'district': districtId,
          },
        );
        dataFinal = data;
      }
      final registerList =
          dataFinal.map((e) => RegisterModel.fromJson(e)).toList();
      return Success(registerList);
    } on DioException catch (e, s) {
      log(
        'DioException em RegisterRepositoryImpl.list',
        name: 'DioException em RegisterRepositoryImpl.list',
        error: e,
        stackTrace: s,
      );
      return Failure(
        RepositoryException(
            message:
                e.message ?? 'DioException em RegisterRepositoryImpl.list'),
      );
    } on ArgumentError catch (e, s) {
      log(
        'ArgumentError em RegisterRepositoryImpl.list',
        name: 'ArgumentError em RegisterRepositoryImpl.list',
        error: e,
        stackTrace: s,
      );
      return Failure(
        RepositoryException(
            message:
                e.message ?? 'ArgumentError em RegisterRepositoryImpl.list'),
      );
    }
  }
}
```
Also follow my pubspec
```
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.2
  riverpod_annotation: ^2.1.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.3.3
  validatorless: ^1.2.3
  intl: ^0.18.1
  url_launcher: ^6.1.14
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^3.0.0-dev.2
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  riverpod_lint: ^2.2.1
  freezed: ^2.4.3
  json_serializable: ^6.7.1

```
**To Reproduce**

**Expected behavior**
That the districtCurrentProvider before and after would not have different effects.

**Sorry to take up your or your colleagues' time if this is a basic error.**
