### ISSUE TITLE
Riverpod Code Generator Issue with library prefixes

### ISSUE THREAD

**Issue by sentd94** [rrousselGit/riverpod#2990]
**Describe the bug**
I've encountered an issue when using the `universal_io` package in conjunction with Riverpod's code generator. Specifically, the File type from universal_io is not being recognized correctly, leading to compilation errors in the generated code.

**To Reproduce**

1. Create a new Flutter project and add both riverpod and universal_io as dependencies.
2. Create a provider utilizing the File type from `universal_io`
3. Run the code generator.

**Expected behavior**
The generated code should recognize the File type from `universal_io` correctly and not produce any compilation errors.

**Actual behaviour**
In the generated code, the File type isn't recognized correctly, leading to compilation errors.

**Versions**
```
Flutter 3.13.5
Dart 3.1.2

environment:
  sdk: '>=3.0.0'
dependencies:
  flutter:
    sdk: flutter
  riverpod_annotation: ^2.0.0   
  hooks_riverpod: ^2.3.5
  flutter_hooks: ^0.18.6
  universal_io: ^2.2.2
dev_dependencies:
  build_runner: ^2.3.3
  custom_lint: ^0.3.2
  riverpod_lint: ^1.1.2
  riverpod_generator: ^2.0.0
  analyzer: ^5.10.0
```

**Example Code**

```dart
import 'package:universal_io/io.dart' as uio;
...
...
@riverpod
class LogoImageFile extends _$LogoImageFile {
  @override
  uio.File? build() {
    return null;
  }

  void setLogoImageFile(uio.File file) {
    if (file.lengthSync() < maxImageSize * 1024 * 1024) {
      state = file;
    }
  }

  void remove() {
    state = null;
  }
}
```

**Example Code - Auto generated**

```dart
/// See also [LogoImageFile].
@ProviderFor(LogoImageFile)
final logoImageFileProvider =
    AutoDisposeNotifierProvider<LogoImageFile, File?>.internal(
  LogoImageFile.new,
  name: r'logoImageFileProvider',
  debugGetCreateSourceHash: const bool.fromEnvironment('dart.vm.product')
      ? null
      : _$logoImageFileHash,
  dependencies: null,
  allTransitiveDependencies: null,
);

typedef _$LogoImageFile = AutoDisposeNotifier<File?>;
```
