### ISSUE TITLE
type '(Arg)' is not a subtype of type 'Arg' in type cast (AutoDisposeFamilyAsyncNotifier)

### ISSUE THREAD

**Issue by Tomburgs** [rrousselGit/riverpod#3063]
**Describe the bug**
We're attempting to mock a provider (using mocktail) and we're running into an issue where when in `AutoDisposeFamilyAsyncNotifier`'s `_setElement` method `element.origin.argument` is cast as `Arg`, however the actual value of the `argument` is `(Arg)` (i.e a record containing `Arg`) which causes the app to crash.

**To Reproduce**

```dart
// Provider
@riverpod
class Foo extends _$Foo {
  @override
  Future<bool> build(Arg arg) async {
    return true;
  }
}

...

// Mock provider
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:mocktail/mocktail.dart';

class MockFoo extends AutoDisposeFamilyAsyncNotifier<bool, Arg> with Mock implements Foo {}

...

// In test pump widget with override.
await tester.pumpWidget(
  ProviderScope(
    overrides: [fooProvider.overrideWith(() => MockFoo())],
    child: MyWidget(),
  )
);
```

**Expected behavior**
`AutoDisposeFamilyAsyncNotifier` should cast the value correctly.

**Version**
```yaml
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter_riverpod: ^3.0.0-dev.0
  riverpod: ^3.0.0-dev.0
  riverpod_annotation: ^3.0.0-dev.0

dev_dependencies:
  riverpod_generator: ^3.0.0-dev.8
```
