### ISSUE TITLE
riverpod_lint is not compatible with flutter_test due to the usage of test_api

### ISSUE THREAD

**Issue by iKK001** [rrousselGit/riverpod#3092]
I try to run `flutter_riverpod` together with `riverpod_lint`.

When I follow the instructions from your readme, then I get the following error during build:

```
So, because your_app depends on both flutter_test from sdk and riverpod_lint ^2.3.3, version solving failed.
```

i.e. as soon as take out `riverpod_lint` then the error dissappears !

My `pubspec.yaml` file looks like this (excerpt) :

```
environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.4  
  riverpod_annotation: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0  
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.5
  custom_lint: ^0.5.6
  riverpod_lint: ^2.3.3
```

Here is more information on what is going wrong - i.e. the rest of the error log looks like this :

```
Note: test_api is pinned to version 0.6.0 by flutter_test from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.

Because test >=1.16.0-nullsafety.19 <1.16.6 depends on test_api 0.2.19 and test >=1.16.6 <1.17.10 depends on analyzer ^1.0.0, test >=1.16.0-nullsafety.19 <1.17.10 requires test_api 0.2.19 or analyzer ^1.0.0.
And because test >=1.17.10 <1.20.0 depends on analyzer >=1.0.0 <3.0.0, test >=1.16.0-nullsafety.19 <1.20.0 requires test_api 0.2.19 or analyzer >=1.0.0 <3.0.0.
And because test >=1.20.0 <1.21.2 depends on test_api 0.4.9 and test >=1.21.0 <1.21.6 depends on analyzer >=2.0.0 <5.0.0, test >=1.16.0-nullsafety.19 <1.21.6 requires analyzer >=1.0.0 <5.0.0 or test_api 0.2.19 or 0.4.9.
Because dev_test >=0.16.2 <0.16.2+3 depends on test >=1.24.6 <3.0.0 and dev_test >=0.15.0 <=0.16.2-1 depends on test >=1.16.2 <3.0.0, dev_test >=0.15.0 <0.16.2+3 requires test >=1.16.2 <3.0.0.
Thus, dev_test >=0.15.0 <0.16.2+3 requires analyzer >=1.0.0 <5.0.0 or test_api 0.2.19 or 0.4.9 or test >=1.21.6 <3.0.0.
And because sqflite_common_ffi_web >=0.3.3+1 depends on dev_test >=0.15.7+2 <2.0.0 and dev_test >=0.16.2+3 depends on test >=1.24.0 <3.0.0, sqflite_common_ffi_web >=0.3.3+1 requires analyzer >=1.0.0 <5.0.0 or test_api 0.2.19 or 0.4.9 or test >=1.21.6 <3.0.0.
Because test >=1.21.6 <1.24.4 depends on analyzer >=2.0.0 <6.0.0 and test >=1.24.4 depends on test_api 0.6.1, test >=1.21.6 requires analyzer >=2.0.0 <6.0.0 or test_api 0.6.1.
Thus, sqflite_common_ffi_web >=0.3.3+1 requires analyzer >=1.0.0 <6.0.0 or test_api 0.2.19 or 0.4.9 or 0.6.1.
And because riverpod_lint >=2.2.1 depends on analyzer ^6.0.0, if riverpod_lint >=2.2.1 and sqflite_common_ffi_web >=0.3.3+1 then test_api 0.2.19 or 0.4.9 or 0.6.1.
And because every version of flutter_test from sdk depends on test_api 0.6.0 and your_app depends on sqflite_common_ffi_web ^0.4.0, riverpod_lint >=2.2.1 is incompatible with flutter_test from sdk.
```

My `analysis_options.yaml` file looks like this:

```
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    constant_identifier_names: false

analyzer:
  plugins:
    - custom_lint
```
