### ISSUE TITLE
container.listen doesn't seems to be invoked in the test code

### ISSUE THREAD

**Issue by yukimatsus** [rrousselGit/riverpod#3186]
**Describe the bug**

The following test code fails.
`container.listen` doesn't seems to be invoked in the test code.

<details>
  <summary>Result(log)</summary>

`'***** container.listen greetingProvider newState: $newState'` does not exist.
It seems that container.listen is not invoked.

```
dart:core             List.last
test/test.dart 26:22  main.<fn>

Bad state: No element
```

</details>

Appendix: With `container.read()` after updating state as described in test.dart, the test passes.

Is this expected behavior?

**To Reproduce**

<details>
  <summary>pubspec.yaml</summary>

```
name: riverpod_unit_test
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
```

</details>

test.dart:

```

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';

final nameProvider = StateProvider((ref) => 'foo');

final greetingProvider = Provider((ref) {
  final name = ref.watch(nameProvider);
  return 'Hello $name';
});

void main() {
  test('test', () {
    final container = ProviderContainer();
    addTearDown(() => container.dispose());

    List<String> notifiedStates = [];
    container.listen(greetingProvider, (oldState, newState) {
      print('***** container.listen greetingProvider newState: $newState');
      notifiedStates.add(newState);
    });

    container.read(nameProvider.notifier).state = 'bar';
    // final _ = container.read(greetingProvider); // If uncomment this line, the test succeed. reference: https://github.com/rrousselGit/riverpod/issues/467
    expect(
      notifiedStates.last,
      'Hello bar',
    );
  });
}
```

**Expected behavior**
This test passes.

Thank you for reading!
