### ISSUE TITLE
Generic state notifier with multiple types

### ISSUE THREAD

**Issue by arcas0803** [rrousselGit/riverpod#3249]
**Describe the bug**
I'm facing an issue when creating a state notifier with multiple generic types.

```
typedef FetchFunction<Result, TParams> = Future<Result> Function(TParams);

@riverpod
class Controllers<CResult, S> extends _$Controllers<CResult, S> {
  @override
  ControllerState<Failure, CResult> build({
    required FetchFunction<Result<CResult>, ControllerParams<S>> fetchFunction,
    ControllerParams<S>? params,
  }) {
    fetch();
    return const Initial();
  }

  Future<void> fetch() async {
    state = const Loading();

    final result = await fetchFunction.call(params ?? const NoParams());

    switch (result) {
      case Success<CResult>(value: final successResult):
        state = Loaded(successResult);
        break;
      case Error<CResult>(
          exception: final errorResult,
        ):
        state = Fail(errorResult);
        break;
    }
  }
}
```
This is a generic notifier to fetch some random stuff.

On generation file i got an error for not casting the fetch function:

```
 @override
  AutoDisposeNotifierProviderElement<Controllers<CResult, S>,
      ControllerState<Failure, CResult>> createElement() {
    return _ControllersProviderElement(this);
  }

  ControllersProvider _copyWith(
    Controllers Function() create,
  ) {
    return ControllersProvider._internal(
      () => create()
        ..fetchFunction = fetchFunction
        ..params = params,
      name: name,
      dependencies: dependencies,
      allTransitiveDependencies: allTransitiveDependencies,
      debugGetCreateSourceHash: debugGetCreateSourceHash,
      from: from,
      fetchFunction: fetchFunction,
      params: params,
    );
  }
```

Error: A value of type 'Future<Result<CResult>> Function(ControllerParams<S>)' can't be assigned to a variable of type 'Future<Result<dynamic>> Function(ControllerParams<dynamic>)'. 

I don't understand why this is happening, because all the values of fetchFunction are of correct type all over the file.

**To Reproduce**

Use the las flutter version and las version of flutter_riverpod, riverpod_generator.

**Comment by rrousselGit** [comment]
Generics aren't supported unless you use the 3.0-dev version

**Comment by arcas0803** [comment]
I'm on 3.0-dev

**Comment by rrousselGit** [comment]
This looks fixed on the current dev branch. I've added a regression test just in case.

**Comment by Gustl22** [comment]
Thanks, works flawless with:

```
dependency_overrides:
  riverpod:
    git:
      url: https://github.com/rrousselGit/riverpod.git
      path: packages/riverpod
      ref: 28d70d0 # dev
  flutter_riverpod:
    git:
      url: https://github.com/rrousselGit/riverpod.git
      path: packages/flutter_riverpod
      ref: 28d70d0 # dev
  riverpod_annotation:
    git:
      url: https://github.com/rrousselGit/riverpod.git
      path: packages/riverpod_annotation
      ref: 28d70d0 # dev
  riverpod_generator:
    git:
      url: https://github.com/rrousselGit/riverpod.git
      path: packages/riverpod_generator
      ref: 28d70d0 # dev
  riverpod_analyzer_utils:
    git:
      url: https://github.com/rrousselGit/riverpod.git
      path: packages/riverpod_analyzer_utils
      ref: 28d70d0 # dev
```
