### ISSUE TITLE
[riverpod_lint] prerelease custom_lint version

### ISSUE THREAD

**Issue by NeroThroN** [rrousselGit/riverpod#3368]
**Describe the bug**
The lastest `riverpod_lint` _(2.3. 9)_ has a new version from Feb 4 with `custom_lint` dependency bumped
but the prerelease of `riverpod_lint` _(3.0.0-dev.4)_ doesn't have this change with the last version from Nov 27

**To Reproduce**
Install the [prerelease](https://pub.dev/packages/riverpod_lint/versions/3.0.0-dev.4) of `riverpod_lint`
Install any other dependency that need `custom_lint ^0.6.2`

Example:
```yaml
dev_dependencies:
  flutter_test:
    sdk: flutter

  custom_lint: 0.6.2
  riverpod_lint: 3.0.0-dev.4
  nilts: 0.12.1   #  <== For example
```

```bash
Resolving dependencies... 
Because nilts 0.12.1 depends on custom_lint_builder ^0.6.0 and riverpod_lint 3.0.0-dev.4 depends on custom_lint_builder ^0.5.2, nilts 0.12.1 is incompatible with riverpod_lint
  3.0.0-dev.4.
```

**Temporarily bypass the problem**
```yaml
dev_dependencies:
  flutter_test:
    sdk: flutter

  custom_lint: 0.6.2
  riverpod_lint: 3.0.0-dev.4
  nilts: 0.12.1

dependency_overrides:
  custom_lint_builder: 0.6.0
  custom_lint_core: 0.6.0
```
