### ISSUE TITLE
riverpod_lint didn't show assists (in context menu)

### ISSUE THREAD

**Issue by Alexqwesa** [rrousselGit/riverpod#3582]
**Description of the bug**
Expected context menu what look like this:
https://raw.githubusercontent.com/rrousselGit/riverpod/master/packages/riverpod_lint/resources/convert_to_consumer_widget.gif

But all i got is "Convert to StatefulWidget"

**To Reproduce**
1. Create new Flutter project
2. with pubspec.yaml
<details>
<summary>pubspec.yaml click me to see</summary>

```yaml
name: test_linter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod:
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  custom_lint:
  riverpod_lint: 
  riverpod_generator:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
```

</details>

3. with analysis_options.yaml
<details>
<summary>analysis_options.yaml click me to see</summary>

```yaml

include: package:flutter_lints/flutter.yaml
analyzer:
  plugins:
    - custom_lint

linter:
  rules:
```
</details>

4.  flutter doctor --verbose
<details>
<summary>flutter doctor --verbose click me to see</summary>

/home/alex/Android/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 3.22.1, on openSUSE Leap 15.5 5.14.21-150500.55.62-default, locale en_US.UTF-8)
    • Flutter version 3.22.1 on channel stable at /home/alex/Android/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (vor 7 Tagen), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/alex/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /home/alex/Android/Sdk
    • Java binary at: /home/alex/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-1/232.10227.8.2321.11479570/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 13.0.1
    • cmake version 3.20.4
    • ninja version 1.10.0
    • pkg-config version 0.29.2

[✓] Android Studio (version 2023.3)
    • Android Studio at /home/alex/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-1/232.10227.8.2321.11479570
    • Flutter plugin version 79.0.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] Android Studio (version 2023.2)
    • Android Studio at /home/alex/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-1/232.10227.8.2321.11280706
    • Flutter plugin version 78.2.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.89.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.88.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • openSUSE Leap 15.5 5.14.21-150500.55.62-default
    • Chrome (web)    • chrome • web-javascript • Google Chrome 125.0.6422.112

[✓] Network resources
    • All expected network resources are available.

• No issues found!
Process finished with exit code 0

</details>

**Expected behavior**
I expect context menu what look like this:
https://raw.githubusercontent.com/rrousselGit/riverpod/master/packages/riverpod_lint/resources/convert_to_consumer_widget.gif
