### ISSUE TITLE
Refactoring Propositions dropping out when updating flutter

### ISSUE THREAD

**Issue by fulstadev** [rrousselGit/riverpod#3680]
**Describe the bug**
Every time I update flutter in my IDE (IntelliJ), the refactorings (e.g. StatefulWidget > ConsumerStatefulWidget) stop showing up for some time, only after doing random stuff like running flutter clean, then flutter pub get, or changing the environment.sdk config in pubspec.yml from sth like  '>=3.3.4 <4.0.0' to '>=3.0.0 <4.0.0' , it starts working again.

**To Reproduce**

I've simply run `flutter upgrade` and the refactorings stopped showing up again. Happened for the 4th time.

My Version Specs:

```
Flutter 3.22.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b0850beeb2 (9 days ago) • 2024-07-16 21:43:41 -0700
Engine • revision 235db911ba
Tools • Dart 3.4.4 • DevTools 2.34.3
```

Configs according to https://riverpod.dev/de/docs/introduction/getting_started for my project:

```
environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk:
        flutter
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner:
  custom_lint:
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
```

Content of analysis_options.yaml:

```
linter:
  rules:

# line added to enable riverpod_lint
analyzer:
  plugins:
    - custom_lint

custom_lint:
  rules:
    - provider_parameters: true
```

Why is the refactoring related to riverpod constantly dropping out? Currently we didn't manage to get it back working. We have not installed any additional packages.
