### ISSUE TITLE
Generator doesn't generate Ref , which deprecation notice says to use

### ISSUE THREAD

**Issue by TonyD-TuftAndPaw** [rrousselGit/riverpod#3801]
**Describe the bug**
In riverpod_generator 2.6.0, `typedef FooRef` is deprecated, and the generated docs say to "Use Ref instead". But `Ref` isn't generated

**To Reproduce**
pubspec.yaml
```
name: sample
publish_to: none
version: 0.0.0+1

environment:
  flutter: 3.24.3
  sdk: 3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1
```

main.dart
```
import 'package:riverpod_annotation/riverpod_annotation.dart';

// 'FooRef' is deprecated and shouldn't be used. Will be removed in 3.0. Use Ref instead. 
@riverpod
bool foo(FooRef ref) {
  return false;
}

// Undefined class 'Ref'
@riverpod
bool bar(Ref ref) {
  return false;
}
```

**Expected behavior**
`Ref` should be generated, so we can clear the dart analysis warnings.
