### ISSUE TITLE
Stream continuously re-created

### ISSUE THREAD

**Issue by yawnt** [rrousselGit/riverpod#4173]
**Describe the bug**

Apologies for the bad bug description, I'm somewhat of a Flutter newbie :(

Logs example with `audioProvider` and `audioPlayerStream` in `ViewModel` once I click toggle

![Image](https://github.com/user-attachments/assets/f159838b-ac71-42f0-945b-70e45045269b)

Logs example with the code block below uncommented once I click toggle

![Image](https://github.com/user-attachments/assets/d6c99669-7638-40b4-963a-7f8287ff922a)

**To Reproduce**

https://dartpad.dev/?id=3fb66f3617b3408ef780e8ba8e919817

```
    // COMMENT LINE BELOW TO SEE STREAM CONTINUOUSLY RECREATING
    final audioPlayer = await ref.watch(audioPlayerProvider.future);
    // END COMMENT
```

**Expected behavior**
The same behaviour with the value incrementing on the screen, given that the provider of the audio player is keep alive and doesn't change.

Tested on 2.6.5

**Comment by yawnt** [comment]
Ok, so I've done a bit more digging. The difference in behaviour between the APIs and the `riverpod_generator` is simpy because I didn't know I needed `StreamProvider.autoDispose<int>` to replicate the same setup as the generator. 

So I guess my question is why does having `ref.watch(audioPlayer)` causes that behaviour in the stream, given that the player is a keep alive and never changes so it should just be cached, am I wrong?

I've amended the original demo to showcase what I mean

**Comment by rrousselGit** [comment]
```dart
    // COMMENT LINE BELOW TO SEE STREAM WORKING
    final audioPlayer = await ref.watch(audioPlayerProvider.future);
    // END COMMENT
    final audioPlayerState = await ref.watch(audioPlayerStreamProvider.future);
```

The issue is the `await` before `ref.watch` combined with auto-dispose.
The provider got disposed during await.

3.0 changes this a bit.
You can read about it in the changelog https://riverpod.dev/docs/whats_new#when-a-provider-rebuilds-its-previous-subscriptions-now-are-kept-until-the-rebuild-completes

This matches this scenario. So closing as intended+fixed :)

**Comment by yawnt** [comment]
Hi,

Thank you so much for your reply!!

I have tried it with 3.0.0-dev16 and I still see the same behaviour. I'm attaching a screenshot of the logs. I haven't changed anything apart from bumping the version to 3.0.0-dev16, running riverpod_generator and rebuilding. I also tried `flutter clean` in case something was off.

Code is the same as Dartpad, just added a log line for when we dispose `audioPlayerStreamProvider`

![Image](https://github.com/user-attachments/assets/569beb6e-1836-4e01-907c-2df163c238a4)

**Comment by yawnt** [comment]
My dependencies:

```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_soloud: ^3.1.10
  freezed_annotation: ^3.0.0-dev.16
  hooks_riverpod: ^3.0.0-dev.16
  riverpod_annotation: ^3.0.0-dev.16
  skeletonizer: ^2.0.1
  tabler_icons_next: ^3.33.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  custom_lint: ^0.7.5
  riverpod_lint: ^3.0.0-dev.16
  build_runner: ^2.4.15
  freezed: ^3.0.6
  riverpod_generator: ^3.0.0-dev.16
  stack_trace: ^1.12.1
```
